importantNutrients = {
    208: {'name': "Calories", 'unit': "kcal", 'minValue': 10, 'benefit': "Provides energy"},
    203: {'name': "Protein", 'unit': "g", 'minValue': 5, 'benefit': "Builds and repairs tissues"},
    204: {'name': "Total Fat", 'unit': "g", 'minValue': 3, 'benefit': "Essential for cell function"},
    606: {'name': "Saturated Fat", 'unit': "g", 'minValue': 1, 'benefit': "Energy storage (limit intake)"},
    205: {'name': "Carbohydrates", 'unit': "g", 'minValue': 15, 'benefit': "Main source of energy"},
    291: {'name': "Fiber", 'unit': "g", 'minValue': 3, 'benefit': "Aids digestion and gut health"},
    269: {'name': "Total Sugars", 'unit': "g", 'minValue': 5, 'benefit': "Provides quick energy"},
    318: {'name': "Vitamin A", 'unit': "µg", 'minValue': 10, 'benefit': "Supports vision and immunity"},
    401: {'name': "Vitamin C", 'unit': "mg", 'minValue': 10, 'benefit': "Boosts immune system"},
    324: {'name': "Vitamin D", 'unit': "IU", 'minValue': 10, 'benefit': "Improves calcium absorption"},
    323: {'name': "Vitamin E", 'unit': "mg", 'minValue': 2, 'benefit': "Protects cells from damage"},
    430: {'name': "Vitamin K", 'unit': "µg", 'minValue': 20, 'benefit': "Helps blood clotting"},
    404: {'name': "Vitamin B1 (Thiamin)", 'unit': "mg", 'minValue': 0.5, 'benefit': "Supports metabolism"},
    405: {'name': "Vitamin B2 (Riboflavin)", 'unit': "mg", 'minValue': 0.5, 'benefit': "Boosts energy levels"},
    406: {'name': "Vitamin B3 (Niacin)", 'unit': "mg", 'minValue': 5, 'benefit': "Maintains skin & nerves"},
    415: {'name': "Vitamin B6", 'unit': "mg", 'minValue': 1, 'benefit': "Brain function & metabolism"},
    418: {'name': "Vitamin B12", 'unit': "µg", 'minValue': 2, 'benefit': "Red blood cell production"},
    417: {'name': "Folate", 'unit': "µg", 'minValue': 100, 'benefit': "Supports cell growth"},
    301: {'name': "Calcium", 'unit': "mg", 'minValue': 100, 'benefit': "Strengthens bones & teeth"},
    303: {'name': "Iron", 'unit': "mg", 'minValue': 2, 'benefit': "Essential for oxygen transport"},
    304: {'name': "Magnesium", 'unit': "mg", 'minValue': 50, 'benefit': "Muscle & nerve function"},
    305: {'name': "Phosphorus", 'unit': "mg", 'minValue': 100, 'benefit': "Supports bones & energy"},
    306: {'name': "Potassium", 'unit': "mg", 'minValue': 200, 'benefit': "Regulates blood pressure"},
    307: {'name': "Sodium", 'unit': "mg", 'minValue': 100, 'benefit': "Fluid balance & nerve signals"},
    309: {'name': "Zinc", 'unit': "mg", 'minValue': 3, 'benefit': "Boosts immunity & healing"}
}
